# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a671119ac2e358650dac92bef915be98ed5c79f87b0b822295ddc91c1d0de8833f91f80e9c1bd7dbec1c3e8936e99b36e8c8c61c9990e8928e8f085d5502fc7

test:
  secret_key_base: 15bde92f7456b2abb3faf62253abdff0f1691db0a292212cc2c551c8ea75d42315f3423f1236a1b235035b7c4e278eb7bd91f03f89ec7f1b7716d2b3ad6897a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
